name: "kernel_On_The_GO"   #Name of the workflow_file

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    name: "Build Kernel"
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout kernel source"
      uses: actions/checkout@v2
      with:
        repository:  priyesh2/kernel_samsung_r8q

    - name: "Set variables"
      id: vars
      run: |
        echo "::set-output name=short_sha::$(git rev-parse HEAD | cut -b 1-8 -)"
        echo "::set-output name=release_name::Storm"
    
    - name: "Android kernel build"
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: ${{ steps.vars.outputs.release_name }}
      with:
        arch: arm64
        compiler: clang/11/binutils
        defconfig: r8q_eur_openx_defconfig
        image: Image.gz-dtb
